# Generated by Django 3.2 on 2023-06-02 17:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20230530_1304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genretitle',
            options={'verbose_name': 'Соответствие жанра и произведения', 'verbose_name_plural': 'Таблица соответствия жанров и произведений'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Оценка ниже допустимой'), django.core.validators.MaxValueValidator(10, message='Оценка выше допустимой')], verbose_name='Oценка'),
        ),
    ]
